import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/providers/ThemeProvider';

const poppins = Poppins({
	variable: '--font-poppins',
	weight: ['400', '500', '600', '700'],
	subsets: ['latin'],
});

const mySite = process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : 'https://jadiael.dev';

export const metadata: Metadata = {
	title: 'Jadiael Juvino | Engenheiro de Software',
	description:
		'Portfólio de Jadiael Juvino, um Engenheiro de Software baseado em Pernambuco, Brasil. Explore meus projetos, habilidades e entre em contato para construirmos algo incrível juntos.',
	keywords: [
		'C#',
		'dotnet',
		'php',
		'nestjs',
		'nextjs',
		'javascript',
		'typescript',
		'wordpress',
		'engenheiro de software',
		'portfólio',
		'Jadiael Juvino',
		'desenvolvedor web',
		'laravel',
		'vps',
		'react',
		'nodejs',
		'frontend',
		'backend',
		'fullstack',
		'desenvolvimento de software',
		'projetos de software',
		'tecnologia',
		'programação',
		'desenvolvedor de software',
		'engenharia de software',
		'desenvolvimento web',
		'desenvolvedor de aplicativos',
		'software solutions',
		'software engineer',
		'web developer',
		'app developer',
		'software development',
		'fullstack developer',
		'frontend developer',
		'backend developer',
		'tech portfolio',
		'software projects',
		'programming skills',
		'software expertise',
		'software consulting',
		'custom software',
		'software architecture',
		'software design',
		'software testing',
		'agile development',
		'scrum',
		'devops',
		'cloud computing',
		'aws',
		'azure',
		'google cloud',
		'database management',
		'sql',
		'nosql',
		'api development',
		'restful api',
		'graphql',
		'microservices',
		'containerization',
		'docker',
		'kubernetes',
		'ci/cd',
		'continuous integration',
		'continuous deployment',
		'version control',
		'git',
		'github',
		'bitbucket',
		'software innovation',
		'tech trends',
		'emerging technologies',
		'software blog',
		'tech blog',
		'coding tutorials',
		'programming tutorials',
		'software education',
		'tech community',
		'open source contributions',
		'software mentorship',
		'career in software',
		'software job market',
		'tech industry insights',
		'software career advice',
		'tech networking',
		'software conferences',
		'tech events',
		'software webinars',
		'online coding bootcamps',
		'software learning resources',
		'tech podcasts',
		'software newsletters',
		'software forums',
		'tech meetups',
		'software hackathons',
		'coding challenges',
		'software competitions',
		'tech scholarships',
		'software internships',
		'tech apprenticeships',
		'software job opportunities',
		'tech freelance work',
		'software remote work',
		'tech digital nomad',
		'software work-life balance',
		'tech productivity tips',
		'software time management',
		'tech career growth',
		'software leadership skills',
		'tech team collaboration',
		'software project management',
		'agile methodologies',
		'scrum master',
		'product owner',
		'software stakeholder management',
		'tech client relations',
		'software business development',
		'tech entrepreneurship',
		'software startup culture',
		'tech innovation labs',
		'software research and development',
		'tech patents',
		'software intellectual property',
		'tech legal issues',
		'software compliance',
		'tech regulations',
		'software ethics',
		'tech social impact',
		'software diversity and inclusion',
		'tech',
	],
	publisher: 'Jadiael Juvino',
	authors: [{ name: 'Jadiael Juvino', url: 'https://jadiael.dev' }],
	creator: 'Jadiael Juvino',
	alternates: {
		canonical: '/',
	},
	robots: 'index, follow',
	icons: [
		{ rel: 'icon', type: 'image/png', sizes: '512x512', url: '/web-app/jadiael_512x512.png' },
		{ rel: 'icon', type: 'image/png', sizes: '256x256', url: '/web-app/jadiael_256x256.png' },
		{ rel: 'icon', type: 'image/png', sizes: '128x128', url: '/web-app/jadiael_128x128.png' },
		{ rel: 'icon', type: 'image/png', sizes: '64x64', url: '/web-app/jadiael_64x64.png' },
		{ rel: 'icon', type: 'image/png', sizes: '32x32', url: '/web-app/jadiael_32x32.png' },
		{ rel: 'icon', type: 'image/png', sizes: '16x16', url: '/web-app/jadiael_16x16.png' },
		{ rel: 'apple-touch-icon', sizes: '180x180', url: '/web-app/jadiael_180x180.png' },
	],
	metadataBase: new URL(mySite),
	openGraph: {
		title: 'Jadiael Juvino | Engenheiro de Software',
		description:
			'Portfólio de Jadiael Juvino, um Engenheiro de Software baseado em Pernambuco, Brasil. Explore meus projetos, habilidades e entre em contato para construirmos algo incrível juntos.',
		url: mySite,
		siteName: 'Jadiael.Dev',
		images: [
			{
				url: `${mySite}/og/site/og1200x630.png`,
				width: 1200,
				height: 630,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/site/og1024x1024.png`,
				width: 1024,
				height: 1024,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/tiktok/og_tiktok_profile_photo200x200.png`,
				width: 200,
				height: 200,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/tiktok/og_tiktok_profile_photo1080x1920.png`,
				width: 200,
				height: 200,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/facebook/og_fb_profile_picture180x180.png`,
				width: 180,
				height: 180,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/facebook/og_fb_image_post1200x630.png`,
				width: 1200,
				height: 630,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/facebook/og_fb_cover_photo820x312.png`,
				width: 820,
				height: 312,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/instagram/insta_square_post1080x1080.png`,
				width: 1080,
				height: 1080,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/instagram/insta_new_post1080x1350.png`,
				width: 1080,
				height: 1350,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/instagram/insta_profile_picture320x320.png`,
				width: 320,
				height: 320,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/instagram/Insta_stories1080x1920.png`,
				width: 320,
				height: 320,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/youtube/youtube_thumb1280x720.png`,
				width: 1280,
				height: 720,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/youtube/youtube_profile_picture800x800.png`,
				width: 800,
				height: 800,
				alt: 'Jadiael.Dev',
			},
			{
				url: `${mySite}/og/youtube/youtube_channel_art2560x1440.png`,
				width: 2560,
				height: 1440,
				alt: 'Jadiael.Dev',
			},
		],
		locale: 'pt-BR',
		type: 'website',
	},
	twitter: {
		card: 'summary',
		title: 'Jadiael Juvino | Engenheiro de Software',
		description:
			'Portfólio de Jadiael Juvino, um Engenheiro de Software baseado em Pernambuco, Brasil. Explore meus projetos, habilidades e entre em contato para construirmos algo incrível juntos.',
		images: [
			{ url: `${mySite}/og/twitter/og_twitter_profile_photo400x400.png`, width: 400, height: 400 },
			{ url: `${mySite}/og/twitter/og_twitter_post_image1200x675.png`, width: 1200, height: 675 },
			{ url: `${mySite}/og/twitter/og_twitter_header1500x500.png`, width: 1500, height: 500 },
		],
		creator: '@Jadiael1',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-BR'>
			<body className={`${poppins.variable} antialiased`}>
				<ThemeProvider>{children}</ThemeProvider>
				<Toaster />
			</body>
		</html>
	);
}
